"""
SP100 company name → ticker mapping.
Covers common variants: full name, short name, brand name.
"""

COMPANY_NAME_TO_TICKER: dict[str, str] = {
    # A
    "apple": "AAPL",
    "abbvie": "ABBV",
    "abbott": "ABT",
    "accenture": "ACN",
    "adobe": "ADBE",
    "aig": "AIG",
    "american international group": "AIG",
    "amd": "AMD",
    "advanced micro devices": "AMD",
    "amgen": "AMGN",
    "american tower": "AMT",
    "amazon": "AMZN",
    "broadcom": "AVGO",
    "american express": "AXP",
    "amex": "AXP",
    "boeing": "BA",
    "bank of america": "BAC",
    "biogen": "BIIB",
    "bank of new york mellon": "BK",
    "bny mellon": "BK",
    "booking holdings": "BKNG",
    "booking.com": "BKNG",
    "blackrock": "BLK",
    "bristol myers squibb": "BMY",
    "bristol-myers squibb": "BMY",
    "berkshire hathaway": "BRK.B",
    "berkshire": "BRK.B",
    "citigroup": "C",
    "citi": "C",
    "caterpillar": "CAT",
    "charter communications": "CHTR",
    "colgate": "CL",
    "colgate-palmolive": "CL",
    "comcast": "CMCSA",
    "capital one": "COF",
    "conocophillips": "COP",
    "costco": "COST",
    "salesforce": "CRM",
    "cisco": "CSCO",
    "cvs health": "CVS",
    "cvs": "CVS",
    "chevron": "CVX",
    "danaher": "DHR",
    "disney": "DIS",
    "walt disney": "DIS",
    "dow": "DOW",
    "dow inc": "DOW",
    "duke energy": "DUK",
    "emerson electric": "EMR",
    "emerson": "EMR",
    "ford": "F",
    "ford motor": "F",
    "fedex": "FDX",
    "general dynamics": "GD",
    "general electric": "GE",
    "ge": "GE",
    "gilead": "GILD",
    "gilead sciences": "GILD",
    "general motors": "GM",
    "gm": "GM",
    "google": "GOOGL",
    "alphabet": "GOOGL",
    "goldman sachs": "GS",
    "goldman": "GS",
    "home depot": "HD",
    "honeywell": "HON",
    "ibm": "IBM",
    "intel": "INTC",
    "intuit": "INTU",
    "johnson & johnson": "JNJ",
    "j&j": "JNJ",
    "jpmorgan": "JPM",
    "jp morgan": "JPM",
    "jpmorgan chase": "JPM",
    "kraft heinz": "KHC",
    "kinder morgan": "KMI",
    "coca-cola": "KO",
    "coca cola": "KO",
    "coke": "KO",
    "linde": "LIN",
    "eli lilly": "LLY",
    "lilly": "LLY",
    "lockheed martin": "LMT",
    "lockheed": "LMT",
    "lowe's": "LOW",
    "lowes": "LOW",
    "mastercard": "MA",
    "mcdonald's": "MCD",
    "mcdonalds": "MCD",
    "mondelez": "MDLZ",
    "medtronic": "MDT",
    "metlife": "MET",
    "meta": "META",
    "facebook": "META",
    "3m": "MMM",
    "altria": "MO",
    "merck": "MRK",
    "morgan stanley": "MS",
    "microsoft": "MSFT",
    "nextera energy": "NEE",
    "nextera": "NEE",
    "netflix": "NFLX",
    "nike": "NKE",
    "nvidia": "NVDA",
    "oracle": "ORCL",
    "pepsico": "PEP",
    "pepsi": "PEP",
    "pfizer": "PFE",
    "procter & gamble": "PG",
    "p&g": "PG",
    "philip morris": "PM",
    "paypal": "PYPL",
    "qualcomm": "QCOM",
    "rtx": "RTX",
    "raytheon": "RTX",
    "starbucks": "SBUX",
    "charles schwab": "SCHW",
    "schwab": "SCHW",
    "southern company": "SO",
    "simon property": "SPG",
    "at&t": "T",
    "att": "T",
    "target": "TGT",
    "thermo fisher": "TMO",
    "thermo fisher scientific": "TMO",
    "t-mobile": "TMUS",
    "tmobile": "TMUS",
    "tesla": "TSLA",
    "texas instruments": "TXN",
    "unitedhealth": "UNH",
    "united health": "UNH",
    "union pacific": "UNP",
    "ups": "UPS",
    "united parcel service": "UPS",
    "us bancorp": "USB",
    "u.s. bancorp": "USB",
    "visa": "V",
    "verizon": "VZ",
    "wells fargo": "WFC",
    "walmart": "WMT",
    "wal-mart": "WMT",
    "exxon": "XOM",
    "exxonmobil": "XOM",
    "exxon mobil": "XOM",
}
